name: Run Tests

on:
  push:
    branches:
      - main
    paths:
      - 'code/pipe/*'
      - 'code/test/*'
  pull_request:
    branches:
      - main
    paths:
      - 'code/pipe/*'
      - 'code/test/*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run filter data tests
      run: python -m unittest test_filter.py
      working-directory: code/test/
