name: Update Data

on:
  schedule:
    - cron: '0 0 * * 0'  # This runs the action every Sunday at midnight
  workflow_dispatch:  # This allows the action to be run manually from the Actions tab

jobs:
  update_data:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
    - name: Run script
      run: python data/load_data.py --api_key ${{ secrets.WOODRUFF_AUTHORIZATION_HEADER }}
    - name: Commit and push if it's not a pull request
      if: github.event_name == 'push' || github.event_name == 'workflow_dispatch' || (github.event_name == 'schedule' && github.repository == github.event.repository.full_name)
      run: |
        git config --global user.name 'Automated'
        git config --global user.email 'actions@users.noreply.github.com'
        git add -A
        timestamp=$(date -u)
        git commit -m "Automated data update $timestamp" || exit 0  # Exit gracefully if there is nothing to commit
        git push
