name: Update Data

on:
  schedule:
    - cron: '0 0 * * 0'  # This runs the action every Sunday at midnight
  workflow_dispatch:  # This allows the action to be run manually from the Actions tab

jobs:
  update_data:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.TYLER_PAT }}  # Use your PAT instead of GITHUB_TOKEN for checkout
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
    - name: Run tests
      run: python -m unittest code/test/test_raw_data.py  # Add this line to run the test
    - name: Run script
      run: python code/pipe/load_data.py --api_key ${{ secrets.WOODRUFF_AUTHORIZATION_HEADER }}
    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
        git add -A
        git commit -m "Automated data update" || exit 0  # Exit gracefully if there is nothing to commit
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.TYLER_PAT }}  # Use your PAT for the push operation
